Refactor convoy-nfs launch script
- Allow nfs to be started using environment vars
- Also, ignore docker volume delete for vfs
- Perform nfs mount in host net namespace

We need to use the host net namespace for the mount command because
if we use the container's net namespace, the source port will get
changed due to NATting and the nfs server will reject the mount
request.

diff --git a/packaging/convoy-agent/launch b/packaging/convoy-agent/launch
--- a/packaging/convoy-agent/launch
+++ b/packaging/convoy-agent/launch
@@ -7,19 +7,23 @@ get_metadata() {
 }
 
 wait_for_metadata() {
-    counter=0
-    printf 'Waiting for metadata'
-    until $(curl --output /dev/null --silent --head --fail http://rancher-metadata); do
-        printf '.'
-        sleep 3
-        counter=$((counter + 1))
-        if [ "$counter" -gt 10 ]; then
-            echo
-            echo "Could not reach metadata." >&2
-            exit 1
-        fi
-    done
-    echo
+    if [ -z "$STACK_NAME" ]; then
+        counter=0
+        printf 'Waiting for metadata'
+        until $(curl --output /dev/null --silent --head --fail http://rancher-metadata); do
+            printf '.'
+            sleep 3
+            counter=$((counter + 1))
+            if [ "$counter" -gt 10 ]; then
+                echo
+                echo "Could not reach metadata." >&2
+                exit 1
+            fi
+        done
+        echo
+    else
+        echo "STACK_NAME env var is set. Will look for all settings as environment variables. Not waiting for metadata."
+    fi
 }
 
 storagepool_agent() {
@@ -39,8 +43,8 @@ storagepool_agent() {
 }
 
 common_vars() {
-    STACK_NAME=$(curl -s http://rancher-metadata/2015-07-25/self/stack/name)
-    STACK_UUID=$(curl -s http://rancher-metadata/2015-07-25/self/stack/uuid)
+    STACK_NAME=${STACK_NAME:-$(curl -s http://rancher-metadata/2015-07-25/self/stack/name)}
+    STACK_UUID=${STACK_UUID:-$(curl -s http://rancher-metadata/2015-07-25/self/stack/uuid)}
     CONVOY_SOCK_IN_CON=/host/var/run/convoy-$STACK_NAME.sock
     CONVOY_SOCK_ON_HOST=/var/run/convoy-$STACK_NAME.sock
     CONVOY_ROOT=/var/lib/rancher/convoy/$STACK_NAME-$STACK_UUID
@@ -144,15 +148,20 @@ volume_driver_longhorn_internal() {
 volume_agent_nfs() {
     wait_for_metadata
     common_vars
-    /var/lib/rancher/convoy-agent/share-mnt $CONVOY_ROOT -- /launch  volume-agent-nfs-internal
+    /var/lib/rancher/convoy-agent/share-mnt $CONVOY_ROOT -- /launch  volume-agent-nfs-internal $PPID
 }
 
 
 volume_agent_nfs_internal() {
+    TARGET_PID=${1?"Cannot run without target pid"}
+
     common_vars
-    MNT_HOST=$(get_metadata nfs_server)
-    MNT_DIR=$(get_metadata mount_dir)
-    MNT_OPTS=$(get_metadata mount_opts)
+    MNT_HOST=${MNT_HOST:-$(get_metadata nfs_server)}
+    MNT_DIR=${MNT_DIR:-$(get_metadata mount_dir)}
+    MNT_OPTS=${MNT_OPTS:-$(get_metadata mount_opts)}
+    if [ -n "$MNT_OPTS" ]; then
+        MNT_OPTS="-o $MNT_OPTS"
+    fi
     MNT_PT=$CONVOY_ROOT/mnt
 
     echo "Registering convoy socket at $CONVOY_SOCK_ON_HOST"
@@ -161,11 +170,8 @@ volume_agent_nfs_internal() {
     echo "Mounting at: $MNT_PT"
     rpcbind
     mkdir -p $MNT_PT
-    if [ -n "$MNT_OPTS" ]; then
-        MNT_OPTS="-o $MNT_OPTS"
-    fi
     echo "Mounting nfs. Command: mount -t nfs $MNT_OPTS $MNT_HOST:$MNT_DIR $MNT_PT"
-    mountpoint -q $MNT_PT || mount -t nfs $MNT_OPTS $MNT_HOST:$MNT_DIR $MNT_PT
+    mountpoint -q $MNT_PT || nsenter -t $TARGET_PID -n mount -t nfs $MNT_OPTS $MNT_HOST:$MNT_DIR $MNT_PT
 
     exec convoy-agent \
         --url $CATTLE_URL \
@@ -176,6 +182,7 @@ volume_agent_nfs_internal() {
         volume \
         --convoy-root $CONVOY_ROOT \
         --convoy-drivers vfs \
+        --convoy-ignore-docker-delete \
         --convoy-driver-opts vfs.path=$MNT_PT
 }
 
